### ISSUE TITLE
Update `develop` with possibly missing bugfixes 

### ISSUE THREAD

**Issue by doekenorg** [GravityKit/GravityExport-Lite#151]
Since `develop` (v2) was built some time ago; there are probably a bunch of issues fixed on `master` that should be backported.

We need to go through these and keep a list on this issue.

- [x] Add missing translations (on new language slug?)
- [x] Javascript no longer works for GravityExport (Filters)
- [x] Migration is run too late, need to fix with transient /option check
- [x] CSS for sorting is not working out due to gravity forms using grid, while we use flex. Rewrite to grid?

**Comment by doekenorg** [comment]
When #156 is merged all is resolved.

**Comment by rafaehlers** [comment]
@doekenorg [I tested v2](https://github.com/GravityKit/GravityExport-Lite/pull/155#issuecomment-1530012419) and the download counter is working:

![image](https://user-images.githubusercontent.com/1222472/235501791-c147b56b-a5d7-4245-ae47-a2885b2f6a7d.png)

**Comment by doekenorg** [comment]
@rafaehlers did you also test if the migrations work? This needs an old installation with a download link set up. Then upgrade the plugin. After that the download link should still work; and the settings should all be still there, but in the new design (best way to check everything works :-) )

**Comment by rafaehlers** [comment]
I remember the migration thing, everything worked as expected, but the download URL didn't work. I had to regenerate that.

**Comment by doekenorg** [comment]
Hmm; that's unfortunate. Was almost the first thing I ported over :S People have these download URL's. They should really work.

- [ ] Fix Migration of download URL
