### ISSUE TITLE
Add a PDF export button to the entry page 

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityExport-Lite#158]
Let's add a button to download the PDF export (if GravityExport is installed ) to the Entry details page (Gravity Form's Entries):

![image](https://user-images.githubusercontent.com/1222472/224131896-3d6294af-d7df-4318-a9f9-695493291341.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2178358326/47540

**Comment by doekenorg** [comment]
@rafaehlers this seems to be fixed by me in v2. It looks like this
<img width="332" alt="Scherm­afbeelding 2023-03-10 om 09 43 54" src="https://user-images.githubusercontent.com/529515/224267465-4fe78bbe-e3ab-4f59-9109-3af1007ba907.png">
