### ISSUE TITLE
Export attached into a notification doesn't follow 

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityExport-Lite#167]
I set this option:

![image](https://github.com/GravityKit/GravityExport-Lite/assets/1222472/453ef2c2-bd4f-4ca1-9591-7b5510013ba7)

with these fields:

![image](https://github.com/GravityKit/GravityExport-Lite/assets/1222472/4482bfef-22af-4013-8876-fc53d963971d)

But the email attachment came with all fields:

![2023-06-02 15-19-43](https://github.com/GravityKit/GravityExport-Lite/assets/1222472/001ac09f-8782-4427-a966-b108be0cd667)

Tested with GF Lite 2.0.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2260969698/49525

**Comment by doekenorg** [comment]
@rafaehlers Do you have this issue yourself as well? Because I remember having this problem myself; before 2.0.0 rolled out, and fixing it. I can also not reproduce this here. It seems to work as advertised. :-) 

Are there any hooks involved?

**Comment by rafaehlers** [comment]
@doekenorg Yes! I reproduced this on debug website: https://debug.gravityview.co/wp-admin/admin.php?subview=gravityexport-lite&page=gf_edit_forms&id=19&view=settings

Don't forget to change the admin notification to your email address before submitting the form.
