### ISSUE TITLE
Gravity Flow conflict: Fatal error when running a specific workflow

### ISSUE THREAD

**Issue by bennemann** [GravityKit/GravityExport-Lite#172]
From a customer:

> The issue is as follows:
> I have set up a Workflow under the form 'Personal Report'.
> 
> First step is when the form comes in an Assignee is selected by the Technical Department. Then the Assignee has to approve the entry (or reject). This step should also allow for reverting of the entry (for example if the Assignee was wrongly assigned, he/she should be able to revert the entry to the assigner).
> 
> Whenever the revert option is carried out the Failure message is prompted:

`Fatal error: Uncaught TypeError: Argument 1 passed to GFExcel\Action\NotificationAttachmentAction::handle_notification() must be of the type array, bool given, called in /home/customer/www/dcnsafe.com/public_html/wp-includes/class-wp-hook.php on line 310 and defined in /home/customer/www/dcnsafe.com/public_html/wp-content/plugins/gf-entries-in-excel/src/Action/NotificationAttachmentAction.php:42 Stack trace: #0 /home/customer/www/dcnsafe.com/public_html/wp-includes/class-wp-hook.php(310): GFExcel\Action\NotificationAttachmentAction->handle_notification(false, Array, Array) #1 /home/customer/www/dcnsafe.com/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array) #2 /home/customer/www/dcnsafe.com/public_html/wp-content/plugins/gravityforms/gravityforms.php(7012): apply_filters('gform_notificat...', false, Array, Array, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) #3 /home/customer/www/dcnsafe.com/public_html/wp-content/plugins/gravityforms/common.php(1964): gf_apply_filters('gform_notificat...', fal in /home/customer/www/dcnsafe.com/public_html/wp-content/plugins/gf-entries-in-excel/src/Action/NotificationAttachmentAction.php on line 42`

Doeke comments:

> Apparently, the hook for the notification is also triggered without the proper notification object. 
> It will probably get false instead of an array, while the hook assumes it is an array. 
> 
> This is an issue that needs resolving on our end.
> 
> But I think it is weird that gform_notification gets triggered without the notification.
> 
> Could be a GravityFlow issue. Either way. We need to fix it in the NotificationAction, and assume the property can also NOT be an array. And adjust accordingly.
>

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2291671487/50199/

**Comment by doekenorg** [comment]
Solved in 2.0.4.
